app:
  site: "localhost"
  devMode: true
  mode: "self"

http:
  host: "localhost"
  port: "8081"
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
  allowedOrigins:
    - "http://localhost"
    - "http://localhost:8081"
    - "http://127.0.0.1:8081"
  allowedMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowedHeaders:
    - "Accept"
    - "Accept-Encoding"
    - "Authorization"
    - "Content-Length"
    - "Content-Type"
    - "X-CSRF-Token"
    - "X-Requested-With"
    - "Origin"
  exposedHeaders:
    - "Content-Length"
    - "Content-Type"
  allowCredentials: true
  proxyHeader: "X-Forwarded-For"
