// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/private/run": {
            "post": {
                "description": "Runs user codes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Run"
                ],
                "summary": "Runs codes.",
                "parameters": [
                    {
                        "description": "Chapter Quest",
                        "name": "quest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.QuestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.QuestChapter": {
            "type": "object",
            "properties": {
                "checkTmp": {
                    "type": "string"
                },
                "dockerTmp": {
                    "type": "string"
                },
                "frontendTmp": {
                    "type": "string"
                },
                "funcname": {
                    "type": "string"
                },
                "userCode": {
                    "type": "string"
                }
            }
        },
        "dto.QuestDTO": {
            "type": "object",
            "properties": {
                "chapter": {
                    "$ref": "#/definitions/dto.QuestChapter"
                },
                "programmingLanguage": {
                    "$ref": "#/definitions/dto.QuestProgrammingLang"
                },
                "tests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.QuestTest"
                    }
                }
            }
        },
        "dto.QuestProgrammingLang": {
            "type": "object",
            "properties": {
                "fileExtention": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.QuestTest": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                }
            }
        },
        "response.BaseResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "dataCount": {
                    "type": "integer"
                },
                "errors": {},
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "session_id",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost",
	BasePath:         "/compiler-api/v1",
	Schemes:          []string{},
	Title:            "API Service",
	Description:      "API Service for Codex-Compiler",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
