basePath: /compiler-api/v1
definitions:
  dto.QuestChapter:
    properties:
      checkTmp:
        type: string
      dockerTmp:
        type: string
      frontendTmp:
        type: string
      funcname:
        type: string
      userCode:
        type: string
    type: object
  dto.QuestDTO:
    properties:
      chapter:
        $ref: '#/definitions/dto.QuestChapter'
      programmingLanguage:
        $ref: '#/definitions/dto.QuestProgrammingLang'
      tests:
        items:
          $ref: '#/definitions/dto.QuestTest'
        type: array
    type: object
  dto.QuestProgrammingLang:
    properties:
      fileExtention:
        type: string
      name:
        type: string
    type: object
  dto.QuestTest:
    properties:
      input:
        type: string
      output:
        type: string
    type: object
  response.BaseResponse:
    properties:
      data: {}
      dataCount:
        type: integer
      errors: {}
      message:
        type: string
      statusCode:
        type: integer
    type: object
host: localhost
info:
  contact: {}
  description: API Service for Codex-Compiler
  title: API Service
paths:
  /private/run:
    post:
      consumes:
      - application/json
      description: Runs user codes.
      parameters:
      - description: Chapter Quest
        in: body
        name: quest
        required: true
        schema:
          $ref: '#/definitions/dto.QuestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Runs codes.
      tags:
      - Run
securityDefinitions:
  ApiKeyAuth:
    in: cookie
    name: session_id
    type: apiKey
swagger: "2.0"
