basePath: /compiler-api/v1
host: localhost
info:
  contact: {}
  description: API Service for Codex-Compiler
  title: API Service
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: cookie
    name: session_id
    type: apiKey
swagger: "2.0"
